# (text, disaster_type, intent, urgency)
D = [
 ("Please help! Our family of 5 is trapped on the second floor near Vijay Nagar. Water is rising quickly and my father is injured. We need rescue immediately.", "Flood", "Emergency Help", "Critical"),
 ("Send boat urgently, 6 people stuck on the roof at Palasia, water above the first floor", "Flood", "Emergency Help", "Critical"),
 ("Elderly grandmother stranded in Bhawarkuan, no food since yesterday, please send help", "Flood", "Emergency Help", "High"),
 ("We need drinking water and food packets at Rau relief camp, 40 people waiting", "Flood", "Emergency Help", "High"),
 ("Flood water has reached the main road near Rajwada", "Flood", "Information", "Low"),
 ("Water level is going down in Sarafa, roads slowly opening", "Flood", "Status Update", "Low"),
 ("Warning: river embankment near Mhow may breach tonight, move to higher ground", "Flood", "Warning", "High"),
 ("Road to the airport blocked by fallen tree, many vehicles stranded", "Flood", "Information", "High"),
 ("Thank you rescue team, our family is safe now at the shelter", "Flood", "Status Update", "Low"),
 ("Praying for everyone affected by the floods. Stay strong Indore", "Flood", "Other", "Low"),
 ("Pregnant woman in labour pain, house surrounded by water in Vijay Nagar, need ambulance now", "Flood", "Emergency Help", "Critical"),
 ("Our colony has no electricity for two days, need shelter for kids", "Flood", "Emergency Help", "High"),
 ("Building collapsed near Palasia, people screaming under the rubble, please send rescue", "Earthquake", "Emergency Help", "Critical"),
 ("Felt strong tremors just now, everyone running out of buildings", "Earthquake", "Information", "Low"),
 ("Aftershock expected, authorities advise staying out of damaged buildings", "Earthquake", "Warning", "High"),
 ("My brother is bleeding badly, trapped under a fallen wall, hurry!", "Earthquake", "Emergency Help", "Critical"),
 ("Hospital in Rau needs blood donors and medicines urgently", "Earthquake", "Emergency Help", "High"),
 ("Cracks in the old school building at Sarafa, please keep children away", "Earthquake", "Warning", "High"),
 ("Earthquake drill at our college today went well", "Earthquake", "Other", "Low"),
 ("Tremors stopped, power restored in Bhawarkuan", "Earthquake", "Status Update", "Low"),
 ("Cyclone landfall in 3 hours, bridge near Mhow is about to collapse, evacuate", "Cyclone", "Warning", "High"),
 ("Roof blown away, 4 people including a baby are exposed to rain, need shelter immediately", "Cyclone", "Emergency Help", "Critical"),
 ("Wind speeds easing now, rain has reduced in Rajwada", "Cyclone", "Status Update", "Low"),
 ("Missing my uncle since the cyclone hit, last seen near Rau, please help find him", "Cyclone", "Emergency Help", "High"),
 ("Fishing boats have returned to the harbour safely", "Cyclone", "Status Update", "Low"),
 ("No one has come to help us for two days, we are tired and angry", "Cyclone", "Emergency Help", "High"),
 ("Huge trees fallen on road, vehicles can't pass near Palasia", "Cyclone", "Information", "High"),
 ("Landslide buried two houses at Mhow hill road, people are trapped, send help fast", "Landslide", "Emergency Help", "Critical"),
 ("Small landslide on highway, one lane blocked, traffic moving slowly", "Landslide", "Information", "Low"),
 ("Old man with heart problem stuck in vehicle behind landslide, no medicine, need doctor", "Landslide", "Emergency Help", "Critical"),
 ("Rocks falling again on the hill road, avoid travelling", "Landslide", "Warning", "High"),
 ("Landslide cleared and road reopened near Bhawarkuan", "Landslide", "Status Update", "Low"),
 ("Need transport to move 10 villagers from the cut-off hamlet to a camp", "Landslide", "Emergency Help", "High"),
 ("Sending love and strength to landslide victims", "Landslide", "Other", "Low"),
 ("Bridge collapsed near Palasia", "Cyclone", "Information", "High"),
 ("Bridge has collapsed in Palasia area", "Cyclone", "Information", "High"),
 ("Bridge collapse reported near Palasia", "Cyclone", "Information", "High"),
]

# Approximate coordinates for the DEMO map only (not real geocoding)
GAZ = {
 "Vijay Nagar": (22.7533, 75.8937), "Palasia": (22.7239, 75.8830),
 "Rajwada": (22.7185, 75.8553), "Bhawarkuan": (22.6960, 75.8680),
 "Sarafa": (22.7176, 75.8553), "Rau": (22.6410, 75.8070),
 "Mhow": (22.5530, 75.7580),
}
